linters:
  enable:
    # default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    # others
    - lll
linter-settings:
  lll:
    line-length: 100
    tab-width: 4
